name: SimonFavorito
favicon: null
layout_spectrum: 0.003972942940890789
typography_spectrum: 0.5552373612299562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#c45a32'
    - '#ce7a5a'
    - '#e7c9be'
    - '#da9f89'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.6943925493396819
  rhythmicContrast: 1
purpose: []
